### PR TITLE
Pin numpy version < 2.0

### LINKED ISSUE #245: numpy v2 not supported
Installing packages brings down numpy version 2, which isn't supported in the code. The CI *should* fail if rerun.

### PR DESCRIPTION
**Pull request by ndalchau**
Closes #245

### CODE REVIEW

**Comment by ndalchau** [comment]
I'm surprised there is a failure for 3.10 when 3.9 and 3.11 work. Is this a flaky test perhaps?

**Comment by timodonnell** [comment]
Yeah sadly we've ended up with some stochastic test failures. Probably some
minor detail like an initializer or something changed at some point in tf
and now some of the model trainings fail occasionally. Need to look into
this.

**Comment by ndalchau** [comment]
Looks like another case of the stochastic test! This time python 3.9 failed.

**Comment by timodonnell** [comment]
Yeah, I'm going to merge this and we can sort out the stochastic test failures separately #248

**Pull request merged**
